version: 2
updates:
  - package-ecosystem: "gomod"
    directory: "/"
    schedule:
      interval: "weekly"
    target-branch: "main"
    ignore:
      - dependency-name: "github.com/ethereum/go-ethereum"
