openapi: 3.0.3
info:
  title: RSS3 Protocol
  version: 0.1.0
  description: RSS3 Protocol is an implementation of the RSS3 Protocol.
components:
  schemas:
    Metadata:
      type: object
      oneOf:
        - allOf: &ref_10
            - type: object
              properties: &ref_0
                address:
                  type: string
                id:
                  type: integer
                  format: int64
                value:
                  type: integer
                  format: int64
                name:
                  type: string
                symbol:
                  type: string
                uri:
                  type: string
                  format: uri
                decimals:
                  type: integer
                parsed_image_url:
                  type: string
                standard:
                  type: string
                  enum: &ref_8
                    - Unknown
                    - ERC-20
                    - ERC-165
                    - ERC-721
                    - ERC-1155
                    - ERC-1967
                    - NEP-141
            - type: object
              properties:
                action:
                  type: string
                  enum: &ref_9
                    - approve
                    - revoke
              required:
                - action
        - allOf: &ref_12
            - type: object
              properties: *ref_0
            - type: string
              enum: &ref_11
                - create
                - bid
                - finalize
                - cancel
                - update
                - invalidate
            - type: object
              properties:
                cost:
                  type: object
                  properties: *ref_0
        - type: object
          properties: *ref_0
        - type: object
          properties: *ref_0
        - type: string
          enum: &ref_13
            - buy
            - sell
            - offer
            - set
            - create
            - finalize
        - type: object
          properties: *ref_0
        - type: object
          properties: &ref_15
            action:
              type: string
              enum: &ref_14
                - add
                - borrow
                - collect
                - remove
                - repay
                - supply
                - withdraw
            tokens:
              type: array
              items:
                type: object
                properties: *ref_0
          required: &ref_16
            - action
            - tokens
        - type: object
          properties: &ref_18
            action:
              type: string
              enum: &ref_17
                - create
                - repay
                - refinance
                - liquidate
                - seize
            collateral:
              type: object
              properties: *ref_0
            amount:
              type: object
              properties: *ref_0
          required: &ref_19
            - action
            - collateral
        - type: object
          properties: &ref_21
            action:
              type: string
              enum: &ref_20
                - stake
                - unstake
                - claim
            token:
              type: object
              properties: *ref_0
            period:
              type: object
              properties:
                start:
                  type: string
                  format: date-time
                end:
                  type: string
                  format: date-time
              required:
                - start
                - end
          required: &ref_22
            - action
            - token
        - properties: &ref_23
            from:
              type: object
              properties: *ref_0
            to:
              type: object
              properties: *ref_0
          type: object
        - type: object
          properties: &ref_1
            id:
              type: string
            body:
              type: string
            start_block:
              type: string
            end_block:
              type: string
            options:
              type: array
              items:
                type: string
            link:
              type: string
          required: &ref_2
            - id
        - type: object
          properties: &ref_25
            action:
              type: string
              enum: &ref_24
                - for
                - against
                - abstain
            token:
              type: object
              properties: *ref_1
              required: *ref_2
            count:
              type: integer
            reason:
              type: string
          required: &ref_26
            - action
            - token
        - type: object
          properties: *ref_0
        - type: object
          properties: *ref_0
        - allOf: &ref_28
            - type: object
              properties: *ref_0
            - type: object
              properties:
                action:
                  type: string
                  enum: &ref_27
                    - buy
                    - list
                    - sell
                cost:
                  type: object
                  properties: *ref_0
        - type: object
          properties: *ref_0
        - type: object
          properties: &ref_29
            title:
              type: string
            description:
              type: string
            pub_date:
              type: string
              format: date-time
            authors:
              type: array
              items:
                type: object
                properties:
                  name:
                    type: string
        - type: object
          properties: &ref_3
            handle:
              type: string
            title:
              type: string
            summary:
              type: string
            body:
              type: string
            media:
              type: array
              items:
                type: object
                properties: &ref_30
                  address:
                    type: string
                  mime_type:
                    type: string
            profile_id:
              type: string
            publication_id:
              type: string
            content_uri:
              type: string
            tags:
              type: array
              items:
                type: string
            author_url:
              type: string
            reward:
              type: object
              properties: *ref_0
            timestamp:
              type: integer
              format: int64
            target:
              type: object
            target_url:
              type: string
        - type: object
          properties: *ref_3
        - type: object
          properties: *ref_3
        - type: object
          properties: *ref_3
        - type: object
          properties: &ref_5
            action:
              type: string
              enum: &ref_4
                - create
                - renew
                - unwrap
                - update
                - wrap
            profile_id:
              type: string
            address:
              type: string
            handle:
              type: string
            image_uri:
              type: string
            bio:
              type: string
            name:
              type: string
            expiry:
              type: string
              format: date-time
            key:
              type: string
            value:
              type: string
        - type: string
          enum: *ref_4
        - type: object
          properties: &ref_32
            action:
              type: string
              enum: &ref_31
                - appoint
                - remove
            proxy_address:
              type: string
            profile:
              type: object
              properties: *ref_5
        - type: object
          properties: *ref_3
        - type: object
          properties: *ref_3
        - type: object
          properties: *ref_3
        - type: object
          properties: &ref_34
            action:
              type: string
              enum: &ref_33
                - approve
                - revoke
            source_network:
              type: string
              enum: &ref_6
                - unknown
                - arbitrum
                - arweave
                - avax
                - base
                - binance-smart-chain
                - bitcoin
                - crossbell
                - ethereum
                - farcaster
                - gnosis
                - linea
                - mastodon
                - near
                - optimism
                - polygon
                - rsshub
                - savm
                - vsl
                - x-layer
              x-go-type: network.Network
              x-go-type-import: &ref_7
                path: github.com/rss3-network/protocol-go/schema/network
            target_network:
              type: string
              enum: *ref_6
              x-go-type: network.Network
              x-go-type-import: *ref_7
            token:
              type: object
              properties: *ref_0
        - type: object
          properties: &ref_36
            action:
              type: string
              enum: &ref_35
                - deposit
                - withdraw
            source_network:
              type: string
              enum: *ref_6
              x-go-type: network.Network
              x-go-type-import: *ref_7
            target_network:
              type: string
              enum: *ref_6
              x-go-type: network.Network
              x-go-type-import: *ref_7
            token:
              type: object
              properties: *ref_0
        - type: object
          properties: *ref_0
        - type: object
          properties: *ref_0
        - type: object
          properties: *ref_0
    Type:
      type: string
      oneOf:
        - type: string
          enum: &ref_37
            - liquidity
            - staking
            - swap
            - loan
        - type: string
          enum: &ref_38
            - approval
            - bridge
            - burn
            - mint
            - transfer
        - type: string
          enum: &ref_39
            - comment
            - delete
            - mint
            - post
            - profile
            - proxy
            - revise
            - reward
            - share
        - type: string
          enum: &ref_40
            - feed
        - type: string
          enum: &ref_41
            - approval
            - burn
            - mint
            - trade
            - transfer
            - auction
        - type: string
          enum: &ref_42
            - unknown
        - type: string
          enum: &ref_43
            - burn
            - mint
            - trade
            - transfer
        - type: string
          enum: &ref_44
            - proposal
            - vote
    Direction:
      type: string
      enum:
        - in
        - out
        - self
      x-go-type: activityx.Direction
      x-go-type-import:
        name: activityx
        path: github.com/rss3-network/protocol-go/schema/activity
    Tag:
      type: string
      enum:
        - unknown
        - collectible
        - exchange
        - governance
        - metaverse
        - rss
        - social
        - transaction
      example: exchange
      x-go-type: tag.Tag
      x-go-type-skip-optional-pointer: true
      x-go-type-import:
        path: github.com/rss3-network/protocol-go/schema/tag
    EthereumChain:
      type: string
      enum:
        - arbitrum
        - avax
        - base
        - binance-smart-chain
        - crossbell
        - gnosis
        - linea
        - ethereum
        - optimism
        - polygon
        - savm
        - vsl
        - x-layer
      x-go-type: network.EthereumChainID
      x-go-type-import:
        path: github.com/rss3-network/protocol-go/schema/network
    Standard:
      type: string
      enum: *ref_8
    Token:
      type: object
      properties: *ref_0
    CollectibleApprovalAction:
      type: string
      enum: *ref_9
    CollectibleApproval:
      allOf: *ref_10
    CollectibleAuctionAction:
      type: string
      enum: *ref_11
    CollectibleAuction:
      allOf: *ref_12
    CollectibleTradeAction:
      type: string
      enum: *ref_13
    ExchangeLiquidityAction:
      type: string
      enum: *ref_14
    ExchangeLiquidity:
      type: object
      properties: *ref_15
      required: *ref_16
    ExchangeLoanAction:
      type: string
      enum: *ref_17
    ExchangeLoan:
      type: object
      properties: *ref_18
      required: *ref_19
    ExchangeStakingAction:
      type: string
      enum: *ref_20
    ExchangeStaking:
      type: object
      properties: *ref_21
      required: *ref_22
    ExchangeSwap:
      properties: *ref_23
      type: object
    GovernanceProposal:
      type: object
      properties: *ref_1
      required: *ref_2
    GovernanceVoteAction:
      type: string
      enum: *ref_24
    GovernanceVote:
      type: object
      properties: *ref_25
      required: *ref_26
    MetaverseTradeAction:
      type: string
      enum: *ref_27
    MetaverseTrade:
      allOf: *ref_28
    RSS:
      type: object
      properties: *ref_29
    Media:
      type: object
      properties: *ref_30
    SocialPost:
      type: object
      properties: *ref_3
    SocialProfileAction:
      type: string
      enum: *ref_4
    SocialProfile:
      type: object
      properties: *ref_5
    SocialProxyAction:
      type: string
      enum: *ref_31
    SocialProxy:
      type: object
      properties: *ref_32
    TransactionApprovalAction:
      type: string
      enum: *ref_33
    Network:
      type: string
      enum: *ref_6
      x-go-type: network.Network
      x-go-type-import: *ref_7
    TransactionApproval:
      type: object
      properties: *ref_34
    TransactionBridgeAction:
      type: string
      enum: *ref_35
    TransactionBridge:
      type: object
      properties: *ref_36
    Exchange:
      type: string
      enum: *ref_37
    Transaction:
      type: string
      enum: *ref_38
    Social:
      type: string
      enum: *ref_39
    RSS-2:
      type: string
      enum: *ref_40
    Collectible:
      type: string
      enum: *ref_41
    Unknown:
      type: string
      enum: *ref_42
    Metaverse:
      type: string
      enum: *ref_43
    Governance:
      type: string
      enum: *ref_44
