// Code generated by "enumer --values --type=SocialType --transform=snake --trimprefix=Social --output social_string.go --json --sql"; DO NOT EDIT.

package typex

import (
	"database/sql/driver"
	"encoding/json"
	"fmt"
	"strings"
)

const _SocialTypeName = "commentdeletemintpostprofileproxyreviserewardsharelike"

var _SocialTypeIndex = [...]uint8{0, 7, 13, 17, 21, 28, 33, 39, 45, 50, 54}

const _SocialTypeLowerName = "commentdeletemintpostprofileproxyreviserewardsharelike"

func (i SocialType) String() string {
	i -= 1
	if i >= SocialType(len(_SocialTypeIndex)-1) {
		return fmt.Sprintf("SocialType(%d)", i+1)
	}
	return _SocialTypeName[_SocialTypeIndex[i]:_SocialTypeIndex[i+1]]
}

func (SocialType) Values() []string {
	return SocialTypeStrings()
}

// An "invalid array index" compiler error signifies that the constant values have changed.
// Re-run the stringer command to generate them again.
func _SocialTypeNoOp() {
	var x [1]struct{}
	_ = x[SocialComment-(1)]
	_ = x[SocialDelete-(2)]
	_ = x[SocialMint-(3)]
	_ = x[SocialPost-(4)]
	_ = x[SocialProfile-(5)]
	_ = x[SocialProxy-(6)]
	_ = x[SocialRevise-(7)]
	_ = x[SocialReward-(8)]
	_ = x[SocialShare-(9)]
	_ = x[SocialLike-(10)]
}

var _SocialTypeValues = []SocialType{SocialComment, SocialDelete, SocialMint, SocialPost, SocialProfile, SocialProxy, SocialRevise, SocialReward, SocialShare, SocialLike}

var _SocialTypeNameToValueMap = map[string]SocialType{
	_SocialTypeName[0:7]:        SocialComment,
	_SocialTypeLowerName[0:7]:   SocialComment,
	_SocialTypeName[7:13]:       SocialDelete,
	_SocialTypeLowerName[7:13]:  SocialDelete,
	_SocialTypeName[13:17]:      SocialMint,
	_SocialTypeLowerName[13:17]: SocialMint,
	_SocialTypeName[17:21]:      SocialPost,
	_SocialTypeLowerName[17:21]: SocialPost,
	_SocialTypeName[21:28]:      SocialProfile,
	_SocialTypeLowerName[21:28]: SocialProfile,
	_SocialTypeName[28:33]:      SocialProxy,
	_SocialTypeLowerName[28:33]: SocialProxy,
	_SocialTypeName[33:39]:      SocialRevise,
	_SocialTypeLowerName[33:39]: SocialRevise,
	_SocialTypeName[39:45]:      SocialReward,
	_SocialTypeLowerName[39:45]: SocialReward,
	_SocialTypeName[45:50]:      SocialShare,
	_SocialTypeLowerName[45:50]: SocialShare,
	_SocialTypeName[50:54]:      SocialLike,
	_SocialTypeLowerName[50:54]: SocialLike,
}

var _SocialTypeNames = []string{
	_SocialTypeName[0:7],
	_SocialTypeName[7:13],
	_SocialTypeName[13:17],
	_SocialTypeName[17:21],
	_SocialTypeName[21:28],
	_SocialTypeName[28:33],
	_SocialTypeName[33:39],
	_SocialTypeName[39:45],
	_SocialTypeName[45:50],
	_SocialTypeName[50:54],
}

// SocialTypeString retrieves an enum value from the enum constants string name.
// Throws an error if the param is not part of the enum.
func SocialTypeString(s string) (SocialType, error) {
	if val, ok := _SocialTypeNameToValueMap[s]; ok {
		return val, nil
	}

	if val, ok := _SocialTypeNameToValueMap[strings.ToLower(s)]; ok {
		return val, nil
	}
	return 0, fmt.Errorf("%s does not belong to SocialType values", s)
}

// SocialTypeValues returns all values of the enum
func SocialTypeValues() []SocialType {
	return _SocialTypeValues
}

// SocialTypeStrings returns a slice of all String values of the enum
func SocialTypeStrings() []string {
	strs := make([]string, len(_SocialTypeNames))
	copy(strs, _SocialTypeNames)
	return strs
}

// IsASocialType returns "true" if the value is listed in the enum definition. "false" otherwise
func (i SocialType) IsASocialType() bool {
	for _, v := range _SocialTypeValues {
		if i == v {
			return true
		}
	}
	return false
}

// MarshalJSON implements the json.Marshaler interface for SocialType
func (i SocialType) MarshalJSON() ([]byte, error) {
	return json.Marshal(i.String())
}

// UnmarshalJSON implements the json.Unmarshaler interface for SocialType
func (i *SocialType) UnmarshalJSON(data []byte) error {
	var s string
	if err := json.Unmarshal(data, &s); err != nil {
		return fmt.Errorf("SocialType should be a string, got %s", data)
	}

	var err error
	*i, err = SocialTypeString(s)
	return err
}

func (i SocialType) Value() (driver.Value, error) {
	return i.String(), nil
}

func (i *SocialType) Scan(value interface{}) error {
	if value == nil {
		return nil
	}

	var str string
	switch v := value.(type) {
	case []byte:
		str = string(v)
	case string:
		str = v
	case fmt.Stringer:
		str = v.String()
	default:
		return fmt.Errorf("invalid value of SocialType: %[1]T(%[1]v)", value)
	}

	val, err := SocialTypeString(str)
	if err != nil {
		return err
	}

	*i = val
	return nil
}
