// Code generated by "enumer --values --type=Tag --transform=snake --trimprefix=Tag --output tag_string.go --json --sql"; DO NOT EDIT.

package tag

import (
	"database/sql/driver"
	"encoding/json"
	"fmt"
	"strings"
)

const _TagName = "unknowncollectibleexchangemetaversersssocialtransactiongovernance"

var _TagIndex = [...]uint8{0, 7, 18, 26, 35, 38, 44, 55, 65}

const _TagLowerName = "unknowncollectibleexchangemetaversersssocialtransactiongovernance"

func (i Tag) String() string {
	if i >= Tag(len(_TagIndex)-1) {
		return fmt.Sprintf("Tag(%d)", i)
	}
	return _TagName[_TagIndex[i]:_TagIndex[i+1]]
}

func (Tag) Values() []string {
	return TagStrings()
}

// An "invalid array index" compiler error signifies that the constant values have changed.
// Re-run the stringer command to generate them again.
func _TagNoOp() {
	var x [1]struct{}
	_ = x[Unknown-(0)]
	_ = x[Collectible-(1)]
	_ = x[Exchange-(2)]
	_ = x[Metaverse-(3)]
	_ = x[RSS-(4)]
	_ = x[Social-(5)]
	_ = x[Transaction-(6)]
	_ = x[Governance-(7)]
}

var _TagValues = []Tag{Unknown, Collectible, Exchange, Metaverse, RSS, Social, Transaction, Governance}

var _TagNameToValueMap = map[string]Tag{
	_TagName[0:7]:        Unknown,
	_TagLowerName[0:7]:   Unknown,
	_TagName[7:18]:       Collectible,
	_TagLowerName[7:18]:  Collectible,
	_TagName[18:26]:      Exchange,
	_TagLowerName[18:26]: Exchange,
	_TagName[26:35]:      Metaverse,
	_TagLowerName[26:35]: Metaverse,
	_TagName[35:38]:      RSS,
	_TagLowerName[35:38]: RSS,
	_TagName[38:44]:      Social,
	_TagLowerName[38:44]: Social,
	_TagName[44:55]:      Transaction,
	_TagLowerName[44:55]: Transaction,
	_TagName[55:65]:      Governance,
	_TagLowerName[55:65]: Governance,
}

var _TagNames = []string{
	_TagName[0:7],
	_TagName[7:18],
	_TagName[18:26],
	_TagName[26:35],
	_TagName[35:38],
	_TagName[38:44],
	_TagName[44:55],
	_TagName[55:65],
}

// TagString retrieves an enum value from the enum constants string name.
// Throws an error if the param is not part of the enum.
func TagString(s string) (Tag, error) {
	if val, ok := _TagNameToValueMap[s]; ok {
		return val, nil
	}

	if val, ok := _TagNameToValueMap[strings.ToLower(s)]; ok {
		return val, nil
	}
	return 0, fmt.Errorf("%s does not belong to Tag values", s)
}

// TagValues returns all values of the enum
func TagValues() []Tag {
	return _TagValues
}

// TagStrings returns a slice of all String values of the enum
func TagStrings() []string {
	strs := make([]string, len(_TagNames))
	copy(strs, _TagNames)
	return strs
}

// IsATag returns "true" if the value is listed in the enum definition. "false" otherwise
func (i Tag) IsATag() bool {
	for _, v := range _TagValues {
		if i == v {
			return true
		}
	}
	return false
}

// MarshalJSON implements the json.Marshaler interface for Tag
func (i Tag) MarshalJSON() ([]byte, error) {
	return json.Marshal(i.String())
}

// UnmarshalJSON implements the json.Unmarshaler interface for Tag
func (i *Tag) UnmarshalJSON(data []byte) error {
	var s string
	if err := json.Unmarshal(data, &s); err != nil {
		return fmt.Errorf("Tag should be a string, got %s", data)
	}

	var err error
	*i, err = TagString(s)
	return err
}

func (i Tag) Value() (driver.Value, error) {
	return i.String(), nil
}

func (i *Tag) Scan(value interface{}) error {
	if value == nil {
		return nil
	}

	var str string
	switch v := value.(type) {
	case []byte:
		str = string(v)
	case string:
		str = v
	case fmt.Stringer:
		str = v.String()
	default:
		return fmt.Errorf("invalid value of Tag: %[1]T(%[1]v)", value)
	}

	val, err := TagString(str)
	if err != nil {
		return err
	}

	*i = val
	return nil
}
