// Code generated by "enumer --values --type=Network --linecomment --output network_string.go --json --yaml --sql"; DO NOT EDIT.

package filter

import (
	"database/sql/driver"
	"encoding/json"
	"fmt"
	"strings"
)

const _NetworkName = "unknownethereumoptimismbasepolygoncrossbellarbitrumrssarweavefarcasteravaxvslsavmbtcbinance_smart_chaingnosislinea"

var _NetworkIndex = [...]uint8{0, 7, 15, 23, 27, 34, 43, 51, 54, 61, 70, 74, 77, 81, 84, 103, 109, 114}

const _NetworkLowerName = "unknownethereumoptimismbasepolygoncrossbellarbitrumrssarweavefarcasteravaxvslsavmbtcbinance_smart_chaingnosislinea"

func (i Network) String() string {
	if i >= Network(len(_NetworkIndex)-1) {
		return fmt.Sprintf("Network(%d)", i)
	}
	return _NetworkName[_NetworkIndex[i]:_NetworkIndex[i+1]]
}

func (Network) Values() []string {
	return NetworkStrings()
}

// An "invalid array index" compiler error signifies that the constant values have changed.
// Re-run the stringer command to generate them again.
func _NetworkNoOp() {
	var x [1]struct{}
	_ = x[NetworkUnknown-(0)]
	_ = x[NetworkEthereum-(1)]
	_ = x[NetworkOptimism-(2)]
	_ = x[NetworkBase-(3)]
	_ = x[NetworkPolygon-(4)]
	_ = x[NetworkCrossbell-(5)]
	_ = x[NetworkArbitrum-(6)]
	_ = x[NetworkRSS-(7)]
	_ = x[NetworkArweave-(8)]
	_ = x[NetworkFarcaster-(9)]
	_ = x[NetworkAvalanche-(10)]
	_ = x[NetworkVSL-(11)]
	_ = x[NetworkSatoshiVM-(12)]
	_ = x[NetworkBTC-(13)]
	_ = x[NetworkBinanceSmartChain-(14)]
	_ = x[NetworkGnosis-(15)]
	_ = x[NetworkLinea-(16)]
}

var _NetworkValues = []Network{NetworkUnknown, NetworkEthereum, NetworkOptimism, NetworkBase, NetworkPolygon, NetworkCrossbell, NetworkArbitrum, NetworkRSS, NetworkArweave, NetworkFarcaster, NetworkAvalanche, NetworkVSL, NetworkSatoshiVM, NetworkBTC, NetworkBinanceSmartChain, NetworkGnosis, NetworkLinea}

var _NetworkNameToValueMap = map[string]Network{
	_NetworkName[0:7]:          NetworkUnknown,
	_NetworkLowerName[0:7]:     NetworkUnknown,
	_NetworkName[7:15]:         NetworkEthereum,
	_NetworkLowerName[7:15]:    NetworkEthereum,
	_NetworkName[15:23]:        NetworkOptimism,
	_NetworkLowerName[15:23]:   NetworkOptimism,
	_NetworkName[23:27]:        NetworkBase,
	_NetworkLowerName[23:27]:   NetworkBase,
	_NetworkName[27:34]:        NetworkPolygon,
	_NetworkLowerName[27:34]:   NetworkPolygon,
	_NetworkName[34:43]:        NetworkCrossbell,
	_NetworkLowerName[34:43]:   NetworkCrossbell,
	_NetworkName[43:51]:        NetworkArbitrum,
	_NetworkLowerName[43:51]:   NetworkArbitrum,
	_NetworkName[51:54]:        NetworkRSS,
	_NetworkLowerName[51:54]:   NetworkRSS,
	_NetworkName[54:61]:        NetworkArweave,
	_NetworkLowerName[54:61]:   NetworkArweave,
	_NetworkName[61:70]:        NetworkFarcaster,
	_NetworkLowerName[61:70]:   NetworkFarcaster,
	_NetworkName[70:74]:        NetworkAvalanche,
	_NetworkLowerName[70:74]:   NetworkAvalanche,
	_NetworkName[74:77]:        NetworkVSL,
	_NetworkLowerName[74:77]:   NetworkVSL,
	_NetworkName[77:81]:        NetworkSatoshiVM,
	_NetworkLowerName[77:81]:   NetworkSatoshiVM,
	_NetworkName[81:84]:        NetworkBTC,
	_NetworkLowerName[81:84]:   NetworkBTC,
	_NetworkName[84:103]:       NetworkBinanceSmartChain,
	_NetworkLowerName[84:103]:  NetworkBinanceSmartChain,
	_NetworkName[103:109]:      NetworkGnosis,
	_NetworkLowerName[103:109]: NetworkGnosis,
	_NetworkName[109:114]:      NetworkLinea,
	_NetworkLowerName[109:114]: NetworkLinea,
}

var _NetworkNames = []string{
	_NetworkName[0:7],
	_NetworkName[7:15],
	_NetworkName[15:23],
	_NetworkName[23:27],
	_NetworkName[27:34],
	_NetworkName[34:43],
	_NetworkName[43:51],
	_NetworkName[51:54],
	_NetworkName[54:61],
	_NetworkName[61:70],
	_NetworkName[70:74],
	_NetworkName[74:77],
	_NetworkName[77:81],
	_NetworkName[81:84],
	_NetworkName[84:103],
	_NetworkName[103:109],
	_NetworkName[109:114],
}

// NetworkString retrieves an enum value from the enum constants string name.
// Throws an error if the param is not part of the enum.
func NetworkString(s string) (Network, error) {
	if val, ok := _NetworkNameToValueMap[s]; ok {
		return val, nil
	}

	if val, ok := _NetworkNameToValueMap[strings.ToLower(s)]; ok {
		return val, nil
	}
	return 0, fmt.Errorf("%s does not belong to Network values", s)
}

// NetworkValues returns all values of the enum
func NetworkValues() []Network {
	return _NetworkValues
}

// NetworkStrings returns a slice of all String values of the enum
func NetworkStrings() []string {
	strs := make([]string, len(_NetworkNames))
	copy(strs, _NetworkNames)
	return strs
}

// IsANetwork returns "true" if the value is listed in the enum definition. "false" otherwise
func (i Network) IsANetwork() bool {
	for _, v := range _NetworkValues {
		if i == v {
			return true
		}
	}
	return false
}

// MarshalJSON implements the json.Marshaler interface for Network
func (i Network) MarshalJSON() ([]byte, error) {
	return json.Marshal(i.String())
}

// UnmarshalJSON implements the json.Unmarshaler interface for Network
func (i *Network) UnmarshalJSON(data []byte) error {
	var s string
	if err := json.Unmarshal(data, &s); err != nil {
		return fmt.Errorf("Network should be a string, got %s", data)
	}

	var err error
	*i, err = NetworkString(s)
	return err
}

// MarshalYAML implements a YAML Marshaler for Network
func (i Network) MarshalYAML() (interface{}, error) {
	return i.String(), nil
}

// UnmarshalYAML implements a YAML Unmarshaler for Network
func (i *Network) UnmarshalYAML(unmarshal func(interface{}) error) error {
	var s string
	if err := unmarshal(&s); err != nil {
		return err
	}

	var err error
	*i, err = NetworkString(s)
	return err
}

func (i Network) Value() (driver.Value, error) {
	return i.String(), nil
}

func (i *Network) Scan(value interface{}) error {
	if value == nil {
		return nil
	}

	var str string
	switch v := value.(type) {
	case []byte:
		str = string(v)
	case string:
		str = v
	case fmt.Stringer:
		str = v.String()
	default:
		return fmt.Errorf("invalid value of Network: %[1]T(%[1]v)", value)
	}

	val, err := NetworkString(str)
	if err != nil {
		return err
	}

	*i = val
	return nil
}
